name: AvilaEnterprises
favicon: null
layout_spectrum: 0.50271
typography_spectrum: 0.683332
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a9311'
    - '#0e0307'
    - '#5edceb'
    - '#d0cd0e'
    - '#e26334'
  brandStrength: 0.928519
  lightness: 0.9093933
  saturation: 0.7532825
  rhythmicContrast: 0.3681955
purpose: []
