name: AvilaEnterprises
favicon: null
layout_spectrum: 0.50271
typography_spectrum: 0.9991
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a9311'
    - '#0e0307'
    - '#5edceb'
    - '#d0cd0e'
    - '#e26334'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
